unit GameLibrary_Intf;

// ----------------------------------------------------------------------
//  This file was automatically generated by Remoting SDK from a
//  RODL file downloaded from a server or associated with this project.
// 
//  Do not modify this file manually, or your changes will be lost when
//  it is regenerated the next time you update your RODL.
// ----------------------------------------------------------------------

{$I RemObjects.inc}

interface

uses
  {$IFDEF DELPHIXE2UP}System.SysUtils{$ELSE}SysUtils{$ENDIF},
  {$IFDEF DELPHIXE2UP}System.Classes{$ELSE}Classes{$ENDIF},
  {$IFDEF DELPHIXE2UP}System.TypInfo{$ELSE}TypInfo{$ENDIF},
  uROEncoding,
  uROUri,
  uROProxy,
  uROExceptions,
  uROXMLIntf,
  uROClasses,
  uROTypes,
  uROClientIntf,
  uROAsync,
  uROEventReceiver;

const LibraryUID: String = '{FF1CABC9-9CD6-4B2D-A05D-7E3671BBB926}';
const DefaultNamespace: String = 'GameLibrary';
const TargetNamespace: String = 'GameLibrary';
const IGameService_IID: TGUID = '{BDC492EC-FB7B-4B72-B511-5D279B12EB66}';
type
  { Forward declarations }
  IGameService = interface;
  IGameService_Async = interface;
  IGameService_AsyncEx = interface;
  CoGameService = class;
  CoGameService_Async = class;
  CoGameService_AsyncEx = class;
  TGameService_Proxy = class;
  TGameService_AsyncProxy = class;
  TGameService_AsyncProxyEx = class;

  IGameService = interface(IROService)
  ['{BDC492EC-FB7B-4B72-B511-5D279B12EB66}']
  end;

  IGameService_Async = interface(IROAsyncInterface)
  end;

  IGameService_AsyncEx = interface(IROAsyncInterfaceEx)
  end;

  CoGameService = class(System.TObject)
  public
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IGameService; overload;
    class function Create(const aUri: TROUri; aDefaultNamespaces: String = ''): IGameService; overload;
    class function Create(const aUrl: String; aDefaultNamespaces: String = ''): IGameService; overload;
  end;

  CoGameService_Async = class(System.TObject)
  public
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IGameService_Async; overload;
    class function Create(const aUri: TROUri; aDefaultNamespaces: String = ''): IGameService_Async; overload;
    class function Create(const aUrl: String; aDefaultNamespaces: String = ''): IGameService_Async; overload;
  end;

  CoGameService_AsyncEx = class(System.TObject)
  public
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IGameService_AsyncEx; overload;
    class function Create(const aUri: TROUri; aDefaultNamespaces: String = ''): IGameService_AsyncEx; overload;
    class function Create(const aUrl: String; aDefaultNamespaces: String = ''): IGameService_AsyncEx; overload;
  end;

  TGameService_Proxy = class(TROProxy, IGameService)
  protected
    function __GetInterfaceName: String; override;
  end;

  TGameService_AsyncProxy = class(TROAsyncProxy, IGameService_Async)
  protected
    function __GetInterfaceName: String; override;
  end;

  TGameService_AsyncProxyEx = class(TROAsyncProxyEx, IGameService_AsyncEx)
  protected
    function __GetInterfaceName: String; override;
  end;

function DefaultNamespaces: String;
implementation

uses
  uROSystem,
  uROSerializer,
  uROClient,
  uROTransportChannel,
  uRORes;

function DefaultNamespaces: String;
var
  lres: String;
begin
  lres := DefaultNamespace;
  result := lres;
  exit;
end;

type
  { Forward declarations }
  TMyTransportChannel = class;

  TMyTransportChannel = class(TROTransportChannel)
  end;

class function CoGameService.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IGameService;
begin
  result := TGameService_Proxy.Create(aMessage, aTransportChannel);
  exit;
end;

class function CoGameService.Create(const aUri: TROUri; aDefaultNamespaces: String = ''): IGameService;
begin
  result := TGameService_Proxy.Create(aUri, aDefaultNamespaces);
  exit;
end;

class function CoGameService.Create(const aUrl: String; aDefaultNamespaces: String = ''): IGameService;
begin
  result := TGameService_Proxy.Create(aUrl, aDefaultNamespaces);
  exit;
end;

class function CoGameService_Async.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IGameService_Async;
begin
  result := TGameService_AsyncProxy.Create(aMessage, aTransportChannel);
  exit;
end;

class function CoGameService_Async.Create(const aUri: TROUri; aDefaultNamespaces: String = ''): IGameService_Async;
begin
  result := TGameService_AsyncProxy.Create(aUri, aDefaultNamespaces);
  exit;
end;

class function CoGameService_Async.Create(const aUrl: String; aDefaultNamespaces: String = ''): IGameService_Async;
begin
  result := TGameService_AsyncProxy.Create(aUrl, aDefaultNamespaces);
  exit;
end;

class function CoGameService_AsyncEx.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IGameService_AsyncEx;
begin
  result := TGameService_AsyncProxyEx.Create(aMessage, aTransportChannel);
  exit;
end;

class function CoGameService_AsyncEx.Create(const aUri: TROUri; aDefaultNamespaces: String = ''): IGameService_AsyncEx;
begin
  result := TGameService_AsyncProxyEx.Create(aUri, aDefaultNamespaces);
  exit;
end;

class function CoGameService_AsyncEx.Create(const aUrl: String; aDefaultNamespaces: String = ''): IGameService_AsyncEx;
begin
  result := TGameService_AsyncProxyEx.Create(aUrl, aDefaultNamespaces);
  exit;
end;

function TGameService_Proxy.__GetInterfaceName: String;
begin
  result := 'GameService';
  exit;
end;

function TGameService_AsyncProxy.__GetInterfaceName: String;
begin
  result := 'GameService';
  exit;
end;

function TGameService_AsyncProxyEx.__GetInterfaceName: String;
begin
  result := 'GameService';
  exit;
end;

initialization
  RegisterProxyClass(IGameService_IID, TGameService_Proxy);
finalization
  UnregisterProxyClass(IGameService_IID);
end.
